### PR TITLE
Revert "ISLANDORA-2004: Makes use of new display aiding predicates"

### PR DESCRIPTION
**Pull request by bondjimbond**
Reverts Islandora/islandora_internet_archive_bookreader#108

Turns out it wasn't so good..? Need to re-test this, sorry.

### CODE REVIEW

**Comment by bondjimbond** [comment]
@DiegoPino I think there might have been a problem with your rebase that I missed... Can we revert and start over?

**Comment by DiegoPino** [comment]
@bondjimbond ok... but not as simple. Would prefer if you could tell me what is not working so I can fix it, instead of going back and forth. You, see the changes are really not too many

**Comment by bondjimbond** [comment]
Hard to say. Now that I look into this as I panic, it seems that it works fine in my Vagrant machine, but when I pull the new code to my production repo it breaks. (View the book, and just get a blank screen or 500 error.) Turn off the BookReader and the page loads. Change to the 7.x-1.10 branch and the Reader is fine.

Can you confirm if it's working OK and just something weird on my site?

I also can no longer find the link to the other PR that went along with this. Can you link me?

**Comment by DiegoPino** [comment]
Maybe its not even this pull. IA Book reader- js issue? Can you please share your PHP error log when that 500 happens? (apache error log) This is the other pull https://github.com/Islandora/islandora_paged_content/pull/132 I'm on a conference so won't be able to react on real time

**Comment by bondjimbond** [comment]
Found the logs!

> [Mon Mar 26 11:13:05.848700 2018] [:error] [pid 38174] [client 162.250.171.91:63574] PHP Fatal error:  Call to undefined function islandora_paged_content_get_viewing_hint() in /opt/rh/httpd24/root/var/www/drupal7/sites/all/modules/islandora_internet_archive_bookreader/theme/theme.inc on line 21

**Comment by bondjimbond** [comment]
It occurs to me now that I may have pulled the Book solution pack instead of Paged Content; I'll check

**Comment by bondjimbond** [comment]
@DiegoPino Yesssss, it works... just me dumbly updating the wrong code. 

OK, gonna close this pull request -- but we should note somehow that you MUST have the updated Paged Content module in order to use the updated IA BookReader.

**Pull request closed without merging**
