### PR TITLE
Work on ISLANDORA-2014.

### PR DESCRIPTION
**Pull request by mjordan**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2014

Companion PR to https://github.com/Islandora/islandora_solution_pack_book/pull/197.

### CODE REVIEW

**Review by DiegoPino — APPROVED** [review]

**Comment by DiegoPino** [comment]
@mjordan let me test both in conjunction before merging. Thanks for this

**Comment by mjordan** [comment]
@Islandora/7-x-1-x-committers I'd love to see this (and accompanying https://github.com/Islandora/islandora_solution_pack_book/pull/197) in the release - any mergers?

**Comment by DiegoPino** [comment]
This one is approved. If someone else can merge both? If not will do in a while before code freeze

**Comment by DiegoPino** [comment]
@mjordan the JIRA ticket was marked as "BUG" so there was really no hurry on this but merged anyway. thanks

**Pull request merged**
