### PR TITLE
Islandora 2436

### PR DESCRIPTION
**Pull request by patdunlavey**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-2436

# What does this Pull Request do?

Makes the IA Bookviewer view mode default to that determined by islandora internet archive bookviewer module.

# What's new?

The "mode" setting is passed into Drupal.behaviors.islandoraInternetArchiveBookReader by template_preprocess_islandora_internet_archive_bookreader(), it is not utilized anywhere to actually set the bookreader view mode. This pull request passes this setting into bookReader.switchMode() to set the viewing mode for the book reader.  

# How should this be tested?

* In an unmodified islandora instance with internet archive bookreader installed and book objects available to view, you should see that no matter what setting is used for "Default page view" at /admin/islandora/islandora_viewers/internet_archive_bookreader, when you go to /islandora/object/[PID], the view will default to 2-up display.
* After applying this change to islandora_internet_archive_bookreader (and ensuring that drupal's javascript cache is cleared), the book object display will switch to the correct mode - either that defined in the islandora_internet_archive_bookreader viewer settings, or in the viewHint of the paged content object being viewed.

# Additional Notes:

* Does this change the interface, add a new feature, or otherwise change behaviours that would require updating documentation? 
_No_
* Does this change add any new dependencies? 
_No_
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? 
_No_
* Could this change impact execution of existing code?
_No_
# Interested parties
@Islandora/7-x-1-x-committers @DiegoPino

### CODE REVIEW

**Comment by DiegoPino** [comment]
@patdunlavey, so 
https://github.com/Islandora/islandora_internet_archive_bookreader/pull/108/files#diff-8964427b21f6180b29573c0367f4b3e6R23 is not working? If you set display mode for an object it does not stick? Is this something recent? We do have that piece working in our repos... would love to know when/how that happened or if this is something different. Thanks

**Comment by patdunlavey** [comment]
Apologies! I forgot that I'm not using the islandora fork of the internet archive bookreader! So nevermind!

**Comment by DiegoPino** [comment]
@patdunlavey no worries! Which fork are you using? =)

**Comment by patdunlavey** [comment]
@DiegoPino I'm using https://github.com/Born-Digital-US/bookreader/tree/2-0-2-BD (to which I just added the mode switching logic). And I also have been using an amalgam of code for islandora_internet_archive_bookreader: https://github.com/patdunlavey/islandora_internet_archive_bookreader/tree/BD-7.x-2.x. I spent a couple hours diddling around to see if maybe I could converge my fork with islandora's, but gave up. I'm thinking I'll just stay forked until I8 rescues us?

**Pull request closed without merging**
