### PR TITLE
ISLANDORA-2023: modified javascript so that it will update the page s…

### PR DESCRIPTION
**Pull request by wgilling**
**JIRA Ticket**: (link)
https://jira.duraspace.org/browse/ISLANDORA-2023 

* Other Relevant Links (Google Groups discussion, related pull requests, Release pull requests, etc.)

# What does this Pull Request do?
This will modify the javascript in the module so that the share link to "Link to this page view:" will be updated when the user navigates to a different page.

A brief description of what the intended result of the PR will be and/or what problem it solves.
The end result should be such that the "Link to this page view:" that is created will reflect the current page -- regardless of how the user navigates to a different page.

# What's new?
A in-depth description of the changes made by this PR. Technical details and possible side effects.
It takes the current location and modifies it using the existing javascript functions in the same unit to update the #pageview element (that is in the hidden "share dialog").

# How should this be tested?
Navigate to a book, click the share button to see what the value for "Link to this page view:" is.  Navigate to that URL to see if it is the correct page.  Navigate to a different page with the pointer or the slide control -- and repeat the steps to confirm that the new "Link to this page view:" points to the new page.

A description of what steps someone could take to:
* Reproduce the problem you are fixing (if applicable)
* Test that the Pull Request does what is intended.
* Please be as detailed as possible.
* Good testing instructions help get your PR completed faster.

# Additional Notes:
It may be helpful to update documentation so that the feature to share a page is mentioned.

# Interested parties
none that I can think of currently, but I am sure that anybody who uses this module would expect that the share link would give you a link to the currently viewed page.

### CODE REVIEW

**Comment by DiegoPino** [comment]
@bgilling @jonathangreen  this pull is against 7.x-1.9 (closed/frozen branch) Needs to be re-done to 7.x branch. Please ping me when ready. Let's see if we get this one into the release =) Thanks!

**Comment by DiegoPino** [comment]
Folks, tomorrow(more like tonightt) is code freeze. This is really a bug so we could have a few more weeks but i really need it to be re-done since this one is still against a release branch and needs to be made against 7.x. @bgilling @jonathangreen pinging you both

**Comment by jonathangreen** [comment]
@bgilling if you want to remake this PR targeting the 7.x branch I will test / code review.

**Comment by DiegoPino** [comment]
@bgilling any updates on this? can you make this pull against 7.x, please 😃 ? What you are fixing here is actually a bug (thanks) so would love to see it go into the 7.x-1.10 release which is also a bit late, so we could have some days left. If you don't want to pursue this please let us know. Gracias!

**Comment by wgilling** [comment]
Yes indeedy... I should be able to get that updated in the next hour.

**Comment by wgilling** [comment]
@DiegoPino -- please let me know if there is anything else I can do.

**Comment by DiegoPino** [comment]
@bgilling i see you closed this. Are you opening a new one or was that a mistake? let me know =) thanks!

**Comment by wgilling** [comment]
That was a mistake.  I inferred that I needed to click that button to post my comment and close the tab.  It should be opened again.

**Comment by DiegoPino** [comment]
@bgilling great. I will keep asking things from you, sorry. I need you to make these changes, the same ones, against the 7.x branch (this pull is against the 7.x-1.9 branch which is frozen). Once that new pull is done and reviewed (and merged) we can then close this one. @jonathangreen assigned himself to review your pull so please mention him once you do this in your pull request message. Take your time and please ping me if you need any assistance. Cheers!

**Comment by wgilling** [comment]
@jonathangreen -- my branch "uls_share_page_fix" should be based from the 7.x.  Please let me know if it is not done correctly this time either.

**Comment by DiegoPino** [comment]
@jonathangreen+++ you changed the base branch! thanks a lot!

**Comment by jonathangreen** [comment]
Hi @bgilling. This pull request was still pointed at the `7.x-1.9` branch, but I just updated it to the `7.x`, so it should be good to go. I will take a look and review.

**Comment by DiegoPino** [comment]
@jonathangreen i did not now the "edit" button could change that. I learned something new here. thanks for that also! @bgilling closer than ever to a merge 😄

**Comment by wgilling** [comment]
I was certain that this was based off of 7.x -- WHAT am I doing wrong?

in an empty directory:

```
git clone https://github.com/Islandora/islandora_internet_archive_bookreader
cd islandora_internet_archive_bookreader/
git checkout 7.x
git remote add ulsdevteam https://github.com/ulsdevteam/islandora_internet_archive_bookreader
git fetch ulsdevteam
git checkout uls_share_page_fix
git reset 7.x --hard
git cherry-pick 78740e27120c7458848560e64843fb871e570cc4
git push -u ulsdevteam --force
```

**Comment by jonathangreen** [comment]
No worries @bgilling, it is a GitHub thing not a git thing. 

This line at the top of the PR:
screen shot 2017-11-03 at 3 13 10 pm

Used to say:
```
bgilling  wants to merge 1 commit into Islandora:7.x-1.9 from ulsdevteam:uls_share_page_fix
```

Its an option you select when you make the pull request, not actually anything to do with git.

We're all good to go now. I'll try to review this next week, so we can get it merged. Thanks so much for the PR, we really appreciate it. This bug has been an issue for me as well.

**Comment by wgilling** [comment]
@jonathangreen - oooooooooooooooooh.  I need a vacation.

**Pull request closed without merging**
